# -*- coding: utf-8 -*-
"""Atividade_Gestao_de_Notas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AilVzv6zvretnfWrzW1tA-ymbF6CcXr3
"""

# Sistema de Gestão de Notas de Alunos

# Função para adicionar as notas
def adicionar_notas():
    notas = []

    quantidade = int(input("Quantas notas deseja inserir? "))

    for i in range(quantidade):
        nota = float(input(f"Digite a {i + 1}ª nota: "))

        # Verifica se a nota está entre 0 e 10
        while nota < 0 or nota > 10:
            print("Nota inválida! Digite uma nota entre 0 e 10.")
            nota = float(input(f"Digite novamente a {i + 1}ª nota: "))

        notas.append(nota)

    return notas


# Função para calcular a média
def calcular_media(notas):
    media = sum(notas) / len(notas)
    return media


# Função para determinar a situação do aluno
def determinar_situacao(media):
    if media >= 7:
        return "Aprovado"
    else:
        return "Reprovado"


# Função para exibir o relatório final
def exibir_relatorio(notas, media, situacao):
    print("\n===== RELATÓRIO FINAL =====")
    print("Notas inseridas:", notas)
    print(f"Média: {media:.2f}")
    print("Situação:", situacao)


# Programa principal
notas = adicionar_notas()
media = calcular_media(notas)
situacao = determinar_situacao(media)

exibir_relatorio(notas, media, situacao)